// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4ISfhC2QEYNxlZGEDZ7GjJBsCaWW8TYY',
    appId: '1:670621327845:web:e836d237e1af8844bd0f0c',
    messagingSenderId: '670621327845',
    projectId: 'dipendra-neptechpal',
    authDomain: 'dipendra-neptechpal.firebaseapp.com',
    storageBucket: 'dipendra-neptechpal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwMQpSOj97NqAccN-h3elnqDdbDdVsu8I',
    appId: '1:670621327845:android:3e002e6fffcebf83bd0f0c',
    messagingSenderId: '670621327845',
    projectId: 'dipendra-neptechpal',
    storageBucket: 'dipendra-neptechpal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc1w68y4BWsYYbAGX-OmXkVeatU2VhOYo',
    appId: '1:670621327845:ios:a355a61b18c598bebd0f0c',
    messagingSenderId: '670621327845',
    projectId: 'dipendra-neptechpal',
    storageBucket: 'dipendra-neptechpal.appspot.com',
    iosClientId:
        '670621327845-j8p1ab2l5pmo6ucib3l6l62fpipvgcro.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc1w68y4BWsYYbAGX-OmXkVeatU2VhOYo',
    appId: '1:670621327845:ios:a355a61b18c598bebd0f0c',
    messagingSenderId: '670621327845',
    projectId: 'dipendra-neptechpal',
    storageBucket: 'dipendra-neptechpal.appspot.com',
    iosClientId:
        '670621327845-j8p1ab2l5pmo6ucib3l6l62fpipvgcro.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo',
  );
}
